name: 'clickhouse_energyhub'
version: '1.0.0'
config-version: 2

# Описание проекта
description: "dbt проект для ClickHouse EnergyHub с DQ проверками"

# Настройки профиля
profile: 'clickhouse_energyhub'

# Пути к моделям
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Пути для артефактов
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Настройки для ClickHouse по слоям
models:
  clickhouse_energyhub:
    raw:
      +materialized: view
      +schema: raw
      +tags: ["raw", "kafka_data"]
    ods:
      +materialized: view
      +schema: ods
      +tags: ["ods", "preprocessed", "dq_checked"]
    dds:
      +materialized: table
      +schema: dds
      +tags: ["dds", "detailed", "business_logic"]
    data_marts:
      +materialized: table
      +schema: data_marts
      +tags: ["data_marts", "aggregated", "bi_ready"]

# Настройки для тестов
tests:
  +store_failures: true
  +severity: warn

# Настройки для seeds
seeds:
  +schema: reference_data

# Настройки для snapshots
snapshots:
  +target_schema: snapshots

# Настройки для анализа
analysis:
  +schema: analysis

# Макросы для DQ проверок
vars:
  # Переменные для DQ проверок
  dq_enabled: true
  dq_schema: "dq_checks"
  dq_failure_threshold: 0.1  # 10% допустимых ошибок
  
  # Настройки для ClickHouse
  clickhouse_database: "default"
  clickhouse_cluster: "dwh_test"
  
  # Настройки для мониторинга
  enable_dq_monitoring: true
  dq_alert_email: "admin@energyhub.local"
  
  # Настройки по слоям
  raw_layer_enabled: true
  ods_layer_enabled: true
  dds_layer_enabled: true
  data_marts_layer_enabled: true
