version: 2

sources:
  - name: raw
    description: "Сырые данные из ClickHouse"
    database: otus_default
    schema: raw_data
    tables:
      - name: energy_consumption
        description: "Сырые данные энергопотребления"
        columns:
          - name: device_id
            description: "Уникальный идентификатор устройства"
            tests:
              - not_null
              - unique
          - name: timestamp
            description: "Временная метка измерения"
            tests:
              - not_null
              - is_timestamp
          - name: energy_kwh
            description: "Потребление энергии в кВт*ч"
            tests:
              - not_null
              - accepted_range:
                  min_value: 0
                  max_value: 1000
          - name: location_id
            description: "Идентификатор локации"
            tests:
              - not_null
              - relationships:
                  to: ref('dim_locations')
                  field: location_id
          - name: device_type
            description: "Тип устройства"
            tests:
              - not_null
              - accepted_values:
                  values: ['smart_meter', 'solar_panel', 'battery_storage', 'wind_turbine']
          - name: voltage_v
            description: "Напряжение в вольтах"
            tests:
              - accepted_range:
                  min_value: 0
                  max_value: 1000
          - name: current_a
            description: "Ток в амперах"
            tests:
              - accepted_range:
                  min_value: 0
                  max_value: 1000
          - name: power_factor
            description: "Коэффициент мощности"
            tests:
              - accepted_range:
                  min_value: 0
                  max_value: 1
          - name: _timestamp
            description: "Временная метка загрузки данных"
            tests:
              - not_null
              - is_timestamp

      - name: devices
        description: "Сырые данные устройств"
        columns:
          - name: device_id
            description: "Уникальный идентификатор устройства"
            tests:
              - not_null
              - unique
          - name: device_name
            description: "Название устройства"
            tests:
              - not_null
          - name: device_type
            description: "Тип устройства"
            tests:
              - not_null
          - name: location_id
            description: "Идентификатор локации"
            tests:
              - not_null
          - name: installation_date
            description: "Дата установки"
            tests:
              - not_null
          - name: status
            description: "Статус устройства"
            tests:
              - not_null

      - name: device_types
        description: "Сырые данные типов устройств"
        columns:
          - name: device_type_id
            description: "Уникальный идентификатор типа устройства"
            tests:
              - not_null
              - unique
          - name: device_type_name
            description: "Название типа устройства"
            tests:
              - not_null
          - name: category
            description: "Категория устройства"
            tests:
              - not_null
          - name: description
            description: "Описание типа устройства"
            tests:
              - not_null

  - name: reference
    description: "Справочные данные"
    database: default
    schema: reference_data
    tables:
      - name: locations
        description: "Справочник локаций"
        columns:
          - name: location_id
            description: "Уникальный идентификатор локации"
            tests:
              - not_null
              - unique
          - name: location_name
            description: "Название локации"
            tests:
              - not_null
          - name: location_type
            description: "Тип локации"
            tests:
              - not_null
          - name: address
            description: "Адрес локации"
            tests:
              - not_null

  - name: kafka
    description: "Данные из Kafka"
    database: default
    schema: kafka_data
    tables:
      - name: devices
        description: "Данные устройств из Kafka"
        columns:
          - name: device_id
            description: "Уникальный идентификатор устройства"
            tests:
              - not_null
              - unique
          - name: device_name
            description: "Название устройства"
            tests:
              - not_null
          - name: device_type
            description: "Тип устройства"
            tests:
              - not_null
          - name: location_id
            description: "Идентификатор локации"
            tests:
              - not_null
          - name: installation_date
            description: "Дата установки"
            tests:
              - not_null
          - name: status
            description: "Статус устройства"
            tests:
              - not_null
