version: 2
sources:
- name: raw
  description: Raw data sources from ClickHouse raw database
  database: raw
  schema: raw
  tables:
  - name: energy_consumption_raw
    description: Table energy_consumption_raw from ClickHouse
    columns: []
  - name: devices_raw
    description: Table devices_raw from ClickHouse
    columns: []
  - name: locations_raw
    description: Table locations_raw from ClickHouse
    columns: []
  - name: raw_devices
    description: Table raw_devices from ClickHouse
    columns: []
  - name: raw_energy_consumption
    description: Table raw_energy_consumption from ClickHouse
    columns: []
  - name: raw_locations
    description: Table raw_locations from ClickHouse
    columns: []
  - name: river_flow
    description: Table river_flow from ClickHouse
    columns: []
  - name: river_flow_local
    description: Table river_flow_local from ClickHouse
    columns: []
  - name: river_flow_mv
    description: Table river_flow_mv from ClickHouse
    columns: []
- name: cdm
  description: Tables from cdm database
  database: cdm
  schema: cdm
  tables:
  - name: cdm_device_performance
    description: Table cdm_device_performance from ClickHouse
    columns: []
  - name: cdm_energy_consumption_daily
    description: Table cdm_energy_consumption_daily from ClickHouse
    columns: []
- name: dds
  description: Tables from dds database
  database: dds
  schema: dds
  tables:
  - name: dds_energy_consumption
    description: Table dds_energy_consumption from ClickHouse
    columns: []
  - name: dds_market_data_clean
    description: Table dds_market_data_clean from ClickHouse
    columns: []
  - name: dds_market_data_view
    description: Table dds_market_data_view from ClickHouse
    columns: []
  - name: dds_river_flow_clean
    description: Table dds_river_flow_clean from ClickHouse
    columns: []
  - name: dds_river_flow_view
    description: Table dds_river_flow_view from ClickHouse
    columns: []
- name: ods
  description: Tables from ods database
  database: ods
  schema: ods
  tables:
  - name: market_data
    description: Table market_data from ClickHouse
    columns: []
  - name: market_data_local
    description: Table market_data_local from ClickHouse
    columns: []
  - name: market_data_mv
    description: Table market_data_mv from ClickHouse
    columns: []
  - name: ods_devices
    description: Table ods_devices from ClickHouse
    columns: []
  - name: ods_energy_consumption
    description: Table ods_energy_consumption from ClickHouse
    columns: []
  - name: ods_locations
    description: Table ods_locations from ClickHouse
    columns: []
