# Placeholder for Kubernetes StatefulSet for ClickHouse
# This will define the deployment of the ClickHouse cluster.
# For production, it's highly recommended to use the ClickHouse operator.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  serviceName: "clickhouse"
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: yandex/clickhouse-server
        ports:
        - containerPort: 8123
        - containerPort: 9000
