version: 2

sources:
  - name: kafka
    description: "Сырые данные из Kafka"
    database: default
    schema: kafka_raw
    
    tables:
      - name: energy_measurements
        description: "Сырые измерения энергопотребления из Kafka"
        columns:
          - name: id
            description: "Уникальный идентификатор измерения"
            tests:
              - not_null
          - name: timestamp
            description: "Временная метка измерения"
            tests:
              - not_null
          - name: energy_consumption
            description: "Потребление энергии в кВт*ч"
            tests:
              - not_null
          - name: voltage
            description: "Напряжение в В"
            tests:
              - not_null
          - name: current
            description: "Ток в А"
            tests:
              - not_null
          - name: power_factor
            description: "Коэффициент мощности"
            tests:
              - not_null
          - name: device_id
            description: "Идентификатор устройства"
            tests:
              - not_null
          - name: location_id
            description: "Идентификатор локации"
            tests:
              - not_null
          - name: _kafka_topic
            description: "Топик Kafka"
            tests:
              - not_null
          - name: _kafka_partition
            description: "Партиция Kafka"
            tests:
              - not_null
          - name: _kafka_offset
            description: "Смещение в Kafka"
            tests:
              - not_null
          - name: _kafka_timestamp
            description: "Временная метка Kafka"
            tests:
              - not_null
          - name: created_at
            description: "Время создания записи"
            tests:
              - not_null
          - name: updated_at
            description: "Время обновления записи"
            tests:
              - not_null
