# Placeholder for Prometheus configuration
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
