version: 2

sources:
  - name: raw
    description: "Сырые данные из ClickHouse"
    database: default
    schema: raw_data
    
    tables:
      - name: energy_measurements
        description: "Сырые измерения энергопотребления"
        columns:
          - name: id
            description: "Уникальный идентификатор измерения"
            tests:
              - not_null
              - unique
          - name: timestamp
            description: "Временная метка измерения"
            tests:
              - not_null
          - name: energy_consumption
            description: "Потребление энергии в кВт*ч"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 10000
          - name: voltage
            description: "Напряжение в В"
            tests:
              - dbt_utils.accepted_range:
                  min_value: 200
                  max_value: 250
          - name: current
            description: "Ток в А"
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 100
          - name: power_factor
            description: "Коэффициент мощности"
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0.8
                  max_value: 1.0
          - name: device_id
            description: "Идентификатор устройства"
            tests:
              - not_null
          - name: location_id
            description: "Идентификатор локации"
            tests:
              - not_null
          - name: created_at
            description: "Время создания записи"
            tests:
              - not_null
          - name: updated_at
            description: "Время обновления записи"
            tests:
              - not_null
