version: 2

models:
  - name: stg_locations
    description: "Staging модель для локаций с DQ проверками"
    columns:
      - name: location_id
        description: "Уникальный идентификатор локации"
        tests:
          - not_null_critical_fields
          - unique_key_fields
      - name: location_name
        description: "Название локации"
        tests:
          - not_null_critical_fields
      - name: region
        description: "Регион"
        tests:
          - not_null_critical_fields
      - name: city
        description: "Город"
        tests:
          - not_null_critical_fields
      - name: country
        description: "Страна"
        tests:
          - not_null_critical_fields
      - name: latitude
        description: "Широта"
        tests:
          - value_range_check:
              min_value: -90
              max_value: 90
      - name: longitude
        description: "Долгота"
        tests:
          - value_range_check:
              min_value: -180
              max_value: 180
      - name: dq_score
        description: "DQ score для качества данных"
        tests:
          - dq_score_threshold:
              threshold: 0.7

  - name: stg_devices
    description: "Staging модель для устройств с DQ проверками"
    columns:
      - name: device_id
        description: "Уникальный идентификатор устройства"
        tests:
          - not_null_critical_fields
          - unique_key_fields
      - name: device_name
        description: "Название устройства"
        tests:
          - not_null_critical_fields
      - name: device_type
        description: "Тип устройства"
        tests:
          - not_null_critical_fields
          - data_consistency_check:
              expected_values: ['sensor', 'meter', 'controller', 'gateway']
      - name: location_id
        description: "Идентификатор локации"
        tests:
          - not_null_critical_fields
      - name: dq_score
        description: "DQ score для качества данных"
        tests:
          - dq_score_threshold:
              threshold: 0.7

  - name: stg_energy_measurements
    description: "Staging модель для измерений энергии с DQ проверками"
    columns:
      - name: id
        description: "Уникальный идентификатор измерения"
        tests:
          - not_null_critical_fields
          - unique_key_fields
      - name: timestamp
        description: "Временная метка измерения"
        tests:
          - not_null_critical_fields
          - temporal_sequence_check
      - name: energy_consumption
        description: "Потребление энергии"
        tests:
          - not_null_critical_fields
          - value_range_check:
              min_value: 0
              max_value: 1000000
      - name: voltage
        description: "Напряжение"
        tests:
          - not_null_critical_fields
          - value_range_check:
              min_value: 0
              max_value: 1000
      - name: current
        description: "Ток"
        tests:
          - not_null_critical_fields
          - value_range_check:
              min_value: 0
              max_value: 10000
      - name: power_factor
        description: "Коэффициент мощности"
        tests:
          - not_null_critical_fields
          - value_range_check:
              min_value: 0
              max_value: 1
      - name: device_id
        description: "Идентификатор устройства"
        tests:
          - not_null_critical_fields
      - name: location_id
        description: "Идентификатор локации"
        tests:
          - not_null_critical_fields
      - name: dq_score
        description: "DQ score для качества данных"
        tests:
          - dq_score_threshold:
              threshold: 0.8
