version: 2

sources:
  - name: reference
    description: "Справочные данные"
    database: default
    schema: reference_data
    
    tables:
      - name: devices
        description: "Справочник устройств"
        columns:
          - name: device_id
            description: "Уникальный идентификатор устройства"
            tests:
              - not_null
              - unique
          - name: device_name
            description: "Название устройства"
            tests:
              - not_null
          - name: device_type_id
            description: "Идентификатор типа устройства"
            tests:
              - not_null
          - name: location_id
            description: "Идентификатор локации"
            tests:
              - not_null
          - name: installation_date
            description: "Дата установки"
            tests:
              - not_null
          - name: power_rating_max
            description: "Максимальная мощность"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 100000
          - name: voltage_standard
            description: "Стандарт напряжения"
            tests:
              - not_null
          - name: status
            description: "Статус устройства"
            tests:
              - not_null
